name: PR Checks
on:
    pull_request:
        branches:
            - main
    # allows you to manually trigger this in GH actions
    workflow_dispatch:

env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any

jobs:
    Test_And_Audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            # goofy wacky fix to get ubuntu across the finish line
            # see: https://github.com/parcel-bundler/lightningcss/issues/335#issuecomment-1309800954
            - name: Install Packages
              run: npm install lightningcss

            # - name: Audit
            #   run: npm audit --audit-level=high

            - name: Formatting
              run: npm run pretty-check

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master

            - name: Create env file
              run: |
                  echo "${{ secrets.ENV_FILE_DEV }}" > .env

            - name: Build
              run: npm run build
